name: My first workflow
on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: List all files
        run: ls -a

      - name: Print Working Directory
        run: pwd

      - name: Create JS File
        run: echo 'console.log("Hello World!");' > app.js

      - name: Run JS File
        run: node app.js

  my-second-job:
    runs-on: ubuntu-latest
    needs: my-first-job
    steps:
      - name: Print NodeJS Version
        run: node -v
      - name: Print all files
        run: ls -a
