name: Deploy Inventory Frontend

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Inventory Frontend Repository
        run: git clone https://github.com/kartikgoyal89/inventory-management-frontend.git .

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci

      - name: Build the Application
        run: npm run build

      - name: Deployment complete
        run: echo "Frontend Deployed Succesfully!"
